WORDLIST = [
    "www", "mail", "ftp", "smtp", "pop", "pop3", "imap", "webmail", "email", "remote",
    "api", "api-v1", "api-v2", "api-v3", "v1", "v2", "v3", "rest", "graphql", "rpc", "grpc",
    "app", "apps", "application", "web", "portal", "dashboard", "console", "management",
    "admin", "administrator", "administration", "panel", "control", "cpanel", "whm", "manage",
    "dev", "develop", "development", "developer", "staging", "stage", "test", "testing",
    "qa", "uat", "uat2", "sandbox", "demo", "preview", "beta", "alpha", "pre", "preprod",
    "docs", "doc", "documentation", "wiki", "help", "support", "kb", "knowledge", "faq",
    "blog", "news", "press", "media", "content", "cms", "wp",
    "shop", "store", "cart", "checkout", "pay", "payments", "billing", "invoice", "orders",
    "auth", "login", "signin", "signup", "register", "account", "accounts", "sso", "id",
    "oauth", "oidc", "saml", "identity", "auth0", "okta",
    "cdn", "static", "assets", "asset", "img", "images", "files", "uploads", "download",
    "cdn1", "cdn2", "cdn3", "s3", "storage", "media2", "static2",
    "status", "uptime", "health", "monitor", "monitoring", "ping", "check", "healthcheck",
    "vpn", "proxy", "gateway", "firewall", "waf", "lb", "loadbalancer", "haproxy",
    "partner", "partners", "affiliate", "affiliates", "reseller",
    "jobs", "careers", "career", "hr", "recruitment", "hiring",
    "git", "gitlab", "github", "bitbucket", "svn", "code", "repo",
    "ci", "cd", "jenkins", "travis", "circleci", "build", "deploy", "pipeline",
    "grafana", "kibana", "elastic", "elasticsearch", "prometheus", "metrics", "logs",
    "splunk", "datadog", "newrelic", "dynatrace", "zabbix", "nagios", "icinga",
    "jira", "confluence", "notion", "trello", "asana", "linear", "clickup",
    "chat", "slack", "teams", "message", "messages", "messaging", "mattermost", "rocketchat",
    "forum", "community", "discourse", "discuss",
    "search", "solr", "opensearch",
    "db", "database", "sql", "mysql", "postgres", "postgresql", "mongo", "mongodb",
    "redis", "cache", "memcache", "memcached", "cassandra", "couchdb",
    "internal", "intranet", "private", "corp", "corporate", "int", "lan",
    "exchange", "owa", "outlook", "office", "autodiscover", "mx", "ns1", "ns2", "ns3", "ns4",
    "rdp", "ssh", "sftp", "ftp2", "ftps", "bastion", "jump",
    "webdav", "caldav", "carddav",
    "mobile", "m", "wap",
    "old", "legacy", "archive", "deprecated", "bak", "backup",
    "new", "next", "future",
    "eu", "us", "uk", "au", "ca", "de", "fr", "jp", "sg", "ap", "na",
    "us-east", "us-west", "eu-west", "ap-southeast",
    "prod", "production", "live", "main",
    "marketing", "sales", "crm", "erp", "salesforce", "hubspot",
    "events", "webinar", "conference", "meeting",
    "newsletter", "subscribe",
    "server1", "server2", "host1", "host2",
    "smtp2", "mx1", "mx2", "relay", "inbound", "outbound",
    "sip", "voip", "pbx", "phone",
    "analytics", "tracking", "pixel", "tag", "gtm",
    "push", "notifications", "ws", "wss", "websocket", "socket", "realtime",
    "investor", "investors", "ir",
    "about", "contact", "legal", "terms", "privacy", "policy",
    "map", "maps", "geocode",
    "stream", "streaming", "video", "media3",
    "test2", "dev2", "stage2", "staging2", "dev3", "staging3",
    "report", "reports", "analytics2",
    "feedback", "survey",
    "launch", "landing",
    "api3", "api4",
    "admin2", "secure", "security",
    "office", "workspace",
    "go", "click", "link", "url", "short",
    "data", "dataset", "ml", "ai", "nlp",
    "phpmyadmin", "pma", "adminer",
    "webmin", "plesk", "directadmin",
    "vault", "consul", "nomad", "k8s", "kubernetes", "rancher", "portainer",
    "mail2", "email2", "smtp3",
    "ftp3", "backup2",
    "www2", "www3", "web2", "web3",
    "api-gateway", "api-proxy",
    "microservice", "service", "services",
    "payment", "stripe", "paypal",
    "crm2", "erp2",
    "staging4", "uat3",
    "preview2", "demo2",
    "internal2", "corp2",
    "noc", "soc", "ops", "devops", "sre",
    "sandbox2", "lab", "labs", "experiment",
    "build2", "release", "releases",
    "mirror", "replica", "standby",
    "contractor", "contractors", "vendor", "vendors",
    "helpdesk", "servicedesk", "ticketing",
    "ecommerce", "marketplace",
    "affiliate2", "promo", "coupon",
    "investor2", "finance", "fintech",
    "cloud", "cloud2",
    "edge", "edge2",
    "cluster", "node", "nodes",
    "origin", "origin2",
    "backend", "frontend",
    "middleware", "broker", "queue", "mq", "rabbitmq", "kafka",
    "cron", "scheduler", "worker", "workers",
    "logger", "logstash", "fluentd",
    "registry", "docker", "harbor",
    "cdn-origin", "media-origin",
    "upload", "download2",
    "webhook", "webhooks", "callback",
    "health2", "ready", "readiness", "liveness",
    "public", "ext", "external",
    "testing2", "qa2",
    "a", "b", "c",
]
